# Generated by Django 2.2 on 2019-06-01 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 54, 52, 528053)),
        ),
        migrations.AlterField(
            model_name='passwordrecoverytoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 54, 52, 526797)),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 54, 52, 527607)),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 54, 52, 527230)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 12, 54, 52, 526062)),
        ),
    ]
