# Generated by Django 2.2 on 2019-06-01 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190601_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 32, 774813)),
        ),
        migrations.AlterField(
            model_name='passwordrecoverytoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 32, 773494)),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 32, 774336)),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 32, 773938)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 32, 772585)),
        ),
    ]
