# Generated by Django 2.2 on 2019-06-01 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190601_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 34, 121980)),
        ),
        migrations.AlterField(
            model_name='passwordrecoverytoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 34, 120648)),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 34, 121543)),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 34, 121149)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 13, 3, 34, 119759)),
        ),
    ]
