# Generated by Django 2.2 on 2019-06-05 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190601_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='display_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='subscription_open',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 47, 52, 843965)),
        ),
        migrations.AlterField(
            model_name='passwordrecoverytoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 47, 52, 842752)),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 47, 52, 843502)),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 47, 52, 843115)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 12, 47, 52, 841858)),
        ),
    ]
