# Generated by Django 2.2 on 2019-06-05 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190605_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 44, 52, 378813)),
        ),
        migrations.AlterField(
            model_name='passwordrecoverytoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 44, 52, 377581)),
        ),
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 44, 52, 378370)),
        ),
        migrations.AlterField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 44, 52, 377976)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 13, 44, 52, 376646)),
        ),
    ]
