# Generated by Django 2.2 on 2019-06-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subscription'),
        ),
    ]
