# Generated by Django 2.2 on 2019-06-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
