# Generated by Django 2.2 on 2019-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link_boleto',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
