# Generated by Django 2.2 on 2019-07-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.FloatField(default=None, null=True),
        ),
    ]
