# Generated by Django 2.2 on 2019-07-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_price2_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price2_date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
