# Generated by Django 2.2 on 2019-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_curadorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='group',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
