# Generated by Django 2.2 on 2019-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userrole_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='group',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
