# Generated by Django 2.2 on 2019-07-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_subscription_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='curadorgroup',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Contest'),
            preserve_default=False,
        ),
    ]
