# Generated by Django 2.2 on 2019-07-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_curadorgroup_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CuradorGroup'),
        ),
    ]
