# Generated by Django 2.2 on 2019-07-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190717_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CuradorGroup'),
        ),
    ]
