# Generated by Django 2.2 on 2019-07-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190717_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='contest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contest'),
        ),
    ]
