# Generated by Django 2.2 on 2019-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userrole_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcelas',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='valor_parcela',
            field=models.FloatField(default=None, null=True),
        ),
    ]
