# Generated by Django 2.2 on 2019-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190813_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parcelas',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
