# Generated by Django 2.2 on 2019-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190813_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_desejada',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
