# Generated by Django 2.2 on 2019-08-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_data_desejada'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_prazo',
            field=models.FloatField(default=None, null=True),
        ),
    ]
