# Generated by Django 2.2 on 2019-09-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190911_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Folder'),
        ),
    ]
