# Generated by Django 2.2 on 2019-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_subscription_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('picture', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=250)),
            ],
        ),
    ]
