# Generated by Django 2.2 on 2019-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_curador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curador',
            name='bio',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='curador',
            name='picture',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
