# Generated by Django 2.2 on 2019-09-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190924_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='curador',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Contest'),
        ),
    ]
