# Generated by Django 2.2 on 2020-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_curador_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
