# Generated by Django 2.2 on 2020-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_userprofile_social_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='has_subscription',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='subscription_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='subscription_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_guest',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
