# Generated by Django 2.2 on 2020-07-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200728_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curador',
            name='bio',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
