# Generated by Django 2.2 on 2020-07-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200728_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curador',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='curador',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Contest'),
        ),
        migrations.AlterField(
            model_name='curador',
            name='picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
