# Generated by Django 2.2 on 2020-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_curador_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curador',
            options={'ordering': ['category_order']},
        ),
        migrations.AddField(
            model_name='curador',
            name='category_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
