# Generated by Django 2.2 on 2020-07-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200730_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curador',
            options={'ordering': ['category_order', 'name']},
        ),
    ]
