# Generated by Django 2.2 on 2020-08-01 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_auto_20200730_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='curadorgroup',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('grades', models.TextField(null=True)),
                ('questions', models.TextField(null=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subscription')),
            ],
        ),
    ]
