# Generated by Django 2.2 on 2020-08-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200801_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='group',
        ),
        migrations.AddField(
            model_name='contest',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='groups',
            field=models.ManyToManyField(to='core.CuradorGroup'),
        ),
    ]
