# Generated by Django 2.2 on 2020-11-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_contest_juri_popular_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juripopular',
            name='evaluators',
        ),
        migrations.CreateModel(
            name='IPJuriPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=1024)),
                ('juri_popular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.JuriPopular')),
            ],
        ),
    ]
