# Generated by Django 2.2 on 2020-11-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20201124_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipjuripopular',
            name='juri_popular',
        ),
        migrations.AddField(
            model_name='ipjuripopular',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaJuriPopular'),
        ),
    ]
